[msbuild]
project = "Lunet.Extensions.Logging.SpectreConsole.sln"
[github]
user = "lunet-io"
repo = "Lunet.Extensions.Logging.SpectreConsole"
[changelog]
owners = "xoofx" # Exclude xoofx from changelog mentions
[coverage]
exclude = ["[*]Wcwidth.*"]